version: '3' 

services:
  nginx:
    image: giesekow/nginx-letsencrypt:latest
    container_name: nginx
    networks:
      nextcloud_network:
        ipv4_address: 172.30.0.2
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
      - onlyoffice
    environment:
      LE_EMAIL: ${LE_EMAIL}
      LE_DOMAINS: ${APP_DOMAIN},${ONLYOFFICE_DOMIAN}
      LE_REDIRECT: ${LE_REDIRECT}
      SSL: ${PROXY_SSL}
    volumes:
      - letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
      - ./sites-available:/etc/nginx/sites-enabled
 
  db:
    image: mariadb
    container_name: nextcloud-mariadb
    networks:
      nextcloud_network:
        ipv4_address: 172.30.0.3
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
  
  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice-server
    networks:
      nextcloud_network:
        ipv4_address: 172.30.0.4
    volumes:
      - onlyoffice:/var/www/onlyoffice/Data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=${ONLYOFFICE_JWT_SECRET}
    extra_hosts:
      - "${APP_DOMAIN}:172.30.0.2"
      - "${ONLYOFFICE_DOMIAN}:172.30.0.2"
  
  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    networks:
      nextcloud_network:
        ipv4_address: 172.30.0.5
    volumes:
      - nextcloud:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=db
      - VIRTUAL_HOST=${APP_DOMAIN}
    extra_hosts:
      - "${APP_DOMAIN}:172.30.0.2"
      - "${ONLYOFFICE_DOMIAN}:172.30.0.2"

volumes:
  nextcloud:
  db:
  onlyoffice:
  letsencrypt:

networks:
  nextcloud_network:
    ipam:
      driver: default
      config:
        - subnet: "172.30.0.0/24"
